### ISSUE TITLE
failed software emulation in vitis : failed to find System Metadata section in   binary_container_1.xclbin

### ISSUE THREAD

**Issue by yangyazhou97** [Xilinx/Vitis-Tutorials#364] opened 2023-02-18 13:24 UTC
The "Emulation-SW" build operation failed and the console said it couldn't find "binary_container.xclbin" file, but I do can find this xclbin file in the path, how can I solve this problem?

**Screenshots**
![Screenshot from 2023-02-18 08-07-46](https://user-images.githubusercontent.com/89854398/219868113-d4fd113e-4eee-444a-aa71-a95bd3ac54e2.png)

**Your environment: **
- OS:  Ubuntu 18.04
- Software Version:  2021.2
- Hardware : ZCU102

**Comment by imrickysu** [comment] 2023-02-20 05:58
Hi @yangyazhou97 , are you trying to reproduce any tutorials in this repo? If so, please share the design name or path. Thanks.

**Comment by yangyazhou97** [comment] 2023-02-20 06:35
Actually, I'm reproducing project form here: https://github.com/ATaylorCEngFIET/Building-Accelerated-Applications-with-Vitis/blob/master/Building%20Accelerated%20Applications%20with%20Vitis%20Lab.pdf

**Comment by imrickysu** [comment] 2023-02-20 08:13
For this generic question, we recommend you ask in forums.xilinx.com. This issue board focuses on the issues introduced by the tutorials in this repository.

Generally, if you use default build settings from the Vitis IDE, the generated xclbin can be emulated. XCLBIN is a container with multiple sections. From the error message, it looks like the xclbin you generated doesn't contain this section. You can check with the lab provider or forums.xilinx.com to help you investigate. I'm closing this issue.

**Closed as completed by imrickysu** 2023-02-20 08:13 UTC
Labels: Generic Questions
