### ISSUE TITLE
Pre-synthesis Control Flow option not available when running C-simulation

### ISSUE THREAD

**Issue by ThomasvdWerff** [Xilinx/Vitis-Tutorials#47] opened 2021-03-03 08:49 UTC
While working on the synth and analysis part of the Vitis HLS getting started tutorial I noticed that one of the options has been removed from the C simulation dialog. See the screenshot attached for comparison. 

Tutorial:
![image](https://user-images.githubusercontent.com/38718720/109778818-8b60f500-7c05-11eb-8e21-9888725b14fc.png)

Current:
![image](https://user-images.githubusercontent.com/38718720/109778741-784e2500-7c05-11eb-81b5-abd0418d834e.png)

Is this option (re)moved? 

Version: 2020.2
Build: 3064766

**Comment by randyh62** [comment] 2021-03-03 15:31
The images were taken from the Vitis HLS 2020.2 tool. Sometimes the dialog box is too small to display all the options. Can you see if you can expand the dialog box by making it longer?

**Comment by ThomasvdWerff** [comment] 2021-03-03 15:39
That's correct. I've tried expanding it as well but without any positive results. I've also tried to select the "ghost"-button a few times but that did not work either. It seems like it really disappeared from the dialog.

**Comment by randyh62** [comment] 2021-03-03 16:06
![image](https://user-images.githubusercontent.com/42045079/109834588-361de700-7bf7-11eb-98cc-ce81a6929cac.png)

Here you can see I am running 2020.2 and it shows up. I don't think there is a setting to disable the option, but I will check into it a little further. Can you say what OS you are working with?

**Comment by ThomasvdWerff** [comment] 2021-03-03 16:08
Windows 10 Education, build 19042. Also thanks for your time.

**Comment by randyh62** [comment] 2021-03-04 00:21
Still verifying, but it looks like it might be a limitation of the Windows build.

**Comment by ThomasvdWerff** [comment] 2021-03-04 12:33
I've received confirmation of the same problem on Windows 10 Pro, build 18363.  Both installations are no longer than a week or two old. On the education OS, I've also activated all the possible licenses. On the Pro version, only the following are activated: "Analyzer, HLS, V_WebPACK"

**Comment by randyh62** [comment] 2021-03-04 14:24
I have confirmed this is a limitation of the Windows version. I will add this to the tutorial instructions. However, it looks like you will have to skip this part of the tutorial.  I will see if there are any other limitations we should be aware of, but please let us know of any other issues you may encounter.

**Comment by Premduth** [comment] 2021-08-18 16:28
Closing as per understanding it is a known issue

**Closed by Premduth** 2021-08-18 16:28 UTC
